export const showdownTheme = {
  background: '#F0F0F0',
  cardBackground: '#FFFFFF',
  text: '#000000',
  secondaryText: '#666666',
  border: '#CCCCCC',
  header: '#4A90E2',
  accent: '#FF6B6B',
  fontFamily: '"Roboto Mono", monospace',
  spacing: 1,
  statColors: {
    hp: '#ff0000',
    attack: '#f08030',
    defense: '#f8d030',
    'special-attack': '#6890f0',
    'special-defense': '#78c850',
    speed: '#f85888'
  },
  pokeballColors: {
    'Poke Ball': { main: '#FF0000' },
    'Great Ball': { main: '#0000FF' },
    'Ultra Ball': { main: '#FFD700' },
    'Master Ball': { main: '#800080' },
    'Safari Ball': { main: '#00FF00' },
    'Level Ball': { main: '#FFA500' },
    'Lure Ball': { main: '#00FFFF' },
    'Moon Ball': { main: '#C0C0C0' },
    'Friend Ball': { main: '#00FF00' },
    'Love Ball': { main: '#FF69B4' },
    'Heavy Ball': { main: '#808080' },
    'Fast Ball': { main: '#FF4500' },
    'Sport Ball': { main: '#FFD700' },
    'Premier Ball': { main: '#FFFFFF' },
    'Repeat Ball': { main: '#FF0000' },
    'Timer Ball': { main: '#FFA500' },
    'Nest Ball': { main: '#228B22' },
    'Net Ball': { main: '#0000FF' },
    'Dive Ball': { main: '#00FFFF' },
    'Luxury Ball': { main: '#FFD700' },
    'Heal Ball': { main: '#FF69B4' },
    'Quick Ball': { main: '#FF4500' },
    'Dusk Ball': { main: '#4B0082' },
    'Cherish Ball': { main: '#FF69B4' },
    'Dream Ball': { main: '#800080' },
    'Beast Ball': { main: '#FFD700' }
  }
} as const; 